# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: עתליה גולדברג - פסיכותרפיה
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "/ataliagoldberg" # the subpath of the site
url: "https://shilons.co.il" # the base hostname & protocol for the site
og_image: /assets/img/profile.jpg
google_analytics: "UA-44525508-6"

header:
  pages:
    - name: אודות
      slug: /
    - name: שיטת טיפול
      slug: methods
    - name: יצירת קשר
      slug: contact
  title: עתליה גולדברג
  subtitle: פסיכותרפיה

footer:
  show_powered_by: false
  contact:
    - icon: fas fa-phone
      value: "0545616740"
      link: tel:0545616740
    - icon: fab fa-whatsapp
      value: שליחת הודעה
      link: https://api.whatsapp.com/send?phone=+97254-561-6740&text=
    - icon: fas fa-map
      value: שלזינגר 10, תל אביב
      link: https://www.google.com/maps/place/Shlesinger+St+10,+Tel+Aviv-Yafo
    - icon: fas fa-envelope
      value: ataliago@gmail.com
      link: mailto:ataliago@gmail.com

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
